INSERT INTO cargo (nome)
VALUES
    ('Desenvolvedor Backend'),
    ('Desenvolvedor Frontend'),
    ('Desenvolvedor Full Stack'),
    ('Engenheiro de Software'),
    ('Arquiteto de Software'),
    ('Desenvolvedor Mobile'),
    ('Engenheiro DevOps'),
    ('Engenheiro de Cloud'),
    ('Administrador de Banco de Dados'),
    ('Analista de Sistemas'),
    ('Analista de Suporte'),
    ('Analista de QA'),
    ('Analista de Dados'),
    ('Cientista de Dados'),
    ('Engenheiro de Dados'),
    ('Especialista em Segurança da Informação'),
    ('Product Manager'),
    ('Product Owner'),
    ('Scrum Master'),
    ('UX Designer'),
    ('UI Designer'),
    ('Analista de Recursos Humanos'),
    ('Recrutador'),
    ('Business Partner de RH'),
    ('Analista de Departamento Pessoal'),
    ('Analista Financeiro'),
    ('Assistente Financeiro'),
    ('Analista Contábil'),
    ('Contador'),
    ('Controller'),
    ('Analista de Marketing'),
    ('Coordenador de Marketing'),
    ('Social Media'),
    ('Designer Gráfico'),
    ('Redator'),
    ('Executivo de Vendas'),
    ('Analista Comercial'),
    ('Consultor Comercial'),
    ('Representante Comercial'),
    ('Gerente de Vendas'),
    ('Analista Jurídico'),
    ('Assistente Jurídico'),
    ('Advogado'),
    ('Analista de Operações'),
    ('Assistente de Operações'),
    ('Supervisor de Operações'),
    ('Analista de Atendimento'),
    ('Assistente de Atendimento'),
    ('Customer Success'),
    ('Gerente de Projetos')
ON CONFLICT (nome) DO NOTHING;
